# Generated by Django 5.2.16 on 2026-08-06 13:45

import django.db.models.deletion
from django.db import migrations, models

DECK_FIELDS = (
    ("draw_pile", "draw", True, False),
    ("discard_pile", "discard", False, False),
    ("player_hand", "player_hand", True, False),
    ("croupier_hand", "dealer_hand", False, True),
)


def migrate_json_decks_to_models(apps, schema_editor):
    Game = apps.get_model("game", "Game")
    Deck = apps.get_model("game", "Deck")
    Card = apps.get_model("game", "Card")

    for game in Game.objects.iterator(chunk_size=200):
        for field_name, zone, default_visible, default_visible_first in DECK_FIELDS:
            payload = getattr(game, field_name) or {}
            if isinstance(payload, dict):
                cards = payload.get("cards", [])
                visible = payload.get("visible", default_visible)
                visible_first = payload.get("visible_first", default_visible_first)
            else:
                cards = payload
                visible = default_visible
                visible_first = default_visible_first

            deck = Deck.objects.create(
                game_id=game.pk,
                zone=zone,
                visible=visible,
                visible_first=visible_first,
            )
            Card.objects.bulk_create(
                [
                    Card(
                        deck_id=deck.pk,
                        value=card["value"],
                        suit=card["suit"],
                        position=position,
                    )
                    for position, card in enumerate(cards)
                ]
            )


def restore_json_decks(apps, schema_editor):
    Game = apps.get_model("game", "Game")
    Deck = apps.get_model("game", "Deck")

    for game in Game.objects.iterator(chunk_size=200):
        update_fields = []
        for field_name, zone, default_visible, default_visible_first in DECK_FIELDS:
            deck = Deck.objects.filter(game_id=game.pk, zone=zone).first()
            if deck is None:
                payload = {
                    "visible": default_visible,
                    "visible_first": default_visible_first,
                    "cards": [],
                }
            else:
                payload = {
                    "visible": deck.visible,
                    "visible_first": deck.visible_first,
                    "cards": [
                        {
                            "value": card.value,
                            "suit": card.suit,
                            "true_value": min(card.value, 10),
                        }
                        for card in deck.cards.order_by("position", "id")
                    ],
                }
            setattr(game, field_name, payload)
            update_fields.append(field_name)
        game.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_movelog_game_created_at_game_profile_game_result_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        choices=[
                            ("draw", "Pioche"),
                            ("discard", "Défausse"),
                            ("player_hand", "Main du joueur"),
                            ("dealer_hand", "Main du croupier"),
                        ],
                        max_length=20,
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                ("visible_first", models.BooleanField(default=False)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decks",
                        to="game.game",
                    ),
                ),
            ],
            options={
                "ordering": ["game_id", "zone"],
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.PositiveSmallIntegerField()),
                (
                    "suit",
                    models.CharField(
                        choices=[
                            ("spades", "Piques"),
                            ("clubs", "Trèfles"),
                            ("hearts", "Cœurs"),
                            ("diamonds", "Carreaux"),
                        ],
                        max_length=8,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="game.deck",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="deck",
            constraint=models.UniqueConstraint(
                fields=("game", "zone"), name="unique_deck_zone_per_game"
            ),
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(
                fields=["deck", "position"], name="game_card_deck_id_177688_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="card",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__gte", 1), ("value__lte", 13)),
                name="card_value_between_1_and_13",
            ),
        ),
        migrations.RunPython(migrate_json_decks_to_models, restore_json_decks),
        migrations.RemoveField(
            model_name="game",
            name="croupier_hand",
        ),
        migrations.RemoveField(
            model_name="game",
            name="discard_pile",
        ),
        migrations.RemoveField(
            model_name="game",
            name="draw_pile",
        ),
        migrations.RemoveField(
            model_name="game",
            name="player_hand",
        ),
    ]
